In [1]:
import numpy as np 
import pandas as pd

In [2]:
dataset=pd.read_csv("ML 3RD CLASS MULTILINEAR REGRESSION.csv")

In [3]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
y=dataset['Profit']

In [5]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [7]:
X=dataset[['R&D Spend', 'Administration', 'Marketing Spend', 'State']]

In [8]:
X.head()

R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
model=LinearRegression()

In [11]:
#model.fit(X,y)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train , X_test , y_train , y_test = train_test_split(X,y ,test_size=0.3,random_state=42)

In [14]:
X_train.shape

(35, 4)

In [15]:
X.shape

(50, 4)

In [16]:
X.head()

R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [17]:
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [18]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [19]:
X_train.head()

R&D Spend  Administration  Marketing Spend       State
6   134615.46       147198.87        127716.82  California
41   27892.92        84710.77        164470.71     Florida
46    1315.46       115816.21        297114.46     Florida
47       0.00       135426.92             0.00  California
15  114523.61       122616.84        261776.23    New York

In [20]:
y_train.head()

6     156122.51
41     77798.83
46     49490.75
47     42559.73
15    129917.04
Name: Profit, dtype: float64

In [21]:
#model.fit(X_train,y_train)

In [22]:
from sklearn.preprocessing import OneHotEncoder

In [23]:
ohe=OneHotEncoder(drop="first")

In [24]:
X_train_new=ohe.fit_transform(X_train[["State"]]).toarray()

In [25]:
X_train_new

array([[0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [26]:
X_test_new=ohe.transform(X_test[["State"]]).toarray()

In [27]:
X_test_new

array([[0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.]])

In [28]:
X_train.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State'], dtype='object')

In [29]:
a=np.array([[1,2],[3,4]])

In [30]:
b=np.array([[5,6],[7,8]])

In [31]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [32]:
a

array([[1, 2],
       [3, 4]])

In [33]:
b

array([[5, 6],
       [7, 8]])

In [34]:
X

R&D Spend  Administration  Marketing Spend       State
0   165349.20       136897.80        471784.10    New York
1   162597.70       151377.59        443898.53  California
2   153441.51       101145.55        407934.54     Florida
3   144372.41       118671.85        383199.62    New York
4   142107.34        91391.77        366168.42     Florida
5   131876.90        99814.71        362861.36    New York
6   134615.46       147198.87        127716.82  California
7   130298.13       145530.06        323876.68     Florida
8   120542.52       148718.95        311613.29    New York
9   123334.88       108679.17        304981.62  California
10  101913.08       110594.11        229160.95     Florida
11  100671.96        91790.61        249744.55  California
12   93863.75       127320.38        249839.44     Florida
13   91992.39       135495.07        252664.93  California
14  119943.24       156547.42        256512.92     Florida
15  114523.61       122616.84        261776.23    New York
16   78013.11       121597.55        264346.06  California
17   94657.16       145077.58        282574.31    New York
18   91749.16       114175.79        294919.57     Florida
19   86419.70       153514.11             0.00    New York
20   76253.86       113867.30        298664.47  California
21   78389.47       153773.43        299737.29    New York
22   73994.56       122782.75        303319.26     Florida
23   67532.53       105751.03        304768.73     Florida
24   77044.01        99281.34        140574.81    New York
25   64664.71       139553.16        137962.62  California
26   75328.87       144135.98        134050.07     Florida
27   72107.60       127864.55        353183.81    New York
28   66051.52       182645.56        118148.20     Florida
29   65605.48       153032.06        107138.38    New York
30   61994.48       115641.28         91131.24     Florida
31   61136.38       152701.92         88218.23    New York
32   63408.86       129219.61         46085.25  California
33   55493.95       103057.49        214634.81     Florida
34   46426.07       157693.92        210797.67  California
35   46014.02        85047.44        205517.64    New York
36   28663.76       127056.21        201126.82     Florida
37   44069.95        51283.14        197029.42  California
38   20229.59        65947.93        185265.10    New York
39   38558.51        82982.09        174999.30  California
40   28754.33       118546.05        172795.67  California
41   27892.92        84710.77        164470.71     Florida
42   23640.93        96189.63        148001.11  California
43   15505.73       127382.30         35534.17    New York
44   22177.74       154806.14         28334.72  California
45    1000.23       124153.04          1903.93    New York
46    1315.46       115816.21        297114.46     Florida
47       0.00       135426.92             0.00  California
48     542.05        51743.15             0.00    New York
49       0.00       116983.80         45173.06  California

In [35]:
X_final=np.hstack((X_train[['R&D Spend', 'Administration', 'Marketing Spend']].values,X_train_new))

In [36]:
model.fit(X_final,y_train)

LinearRegression()

In [37]:
model.coef_

array([ 8.04937292e-01, -9.12577104e-02,  2.80672826e-02,  4.58070775e+02,
       -1.23515673e+03])

In [38]:
model.intercept_

57412.64071380659

In [39]:
X_test_final=np.hstack((X_test[['R&D Spend', 'Administration', 'Marketing Spend']].values,X_test_new))

In [40]:
X_test_final

array([[9.1992390e+04, 1.3549507e+05, 2.5266493e+05, 0.0000000e+00,
        0.0000000e+00],
       [3.8558510e+04, 8.2982090e+04, 1.7499930e+05, 0.0000000e+00,
        0.0000000e+00],
       [6.1994480e+04, 1.1564128e+05, 9.1131240e+04, 1.0000000e+00,
        0.0000000e+00],
       [1.0002300e+03, 1.2415304e+05, 1.9039300e+03, 0.0000000e+00,
        1.0000000e+00],
       [9.4657160e+04, 1.4507758e+05, 2.8257431e+05, 0.0000000e+00,
        1.0000000e+00],
       [5.4205000e+02, 5.1743150e+04, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00],
       [7.5328870e+04, 1.4413598e+05, 1.3405007e+05, 1.0000000e+00,
        0.0000000e+00],
       [6.4664710e+04, 1.3955316e+05, 1.3796262e+05, 0.0000000e+00,
        0.0000000e+00],
       [6.3408860e+04, 1.2921961e+05, 4.6085250e+04, 0.0000000e+00,
        0.0000000e+00],
       [8.6419700e+04, 1.5351411e+05, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00],
       [9.3863750e+04, 1.2732038e+05, 2.4983944e+05, 1.0000000e+00,
        0.00

In [41]:
model.score(X_test_final,y_test)

0.93971080633682

In [42]:
X_train_new

array([[0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [43]:
X_train

R&D Spend  Administration  Marketing Spend       State
6   134615.46       147198.87        127716.82  California
41   27892.92        84710.77        164470.71     Florida
46    1315.46       115816.21        297114.46     Florida
47       0.00       135426.92             0.00  California
15  114523.61       122616.84        261776.23    New York
9   123334.88       108679.17        304981.62  California
16   78013.11       121597.55        264346.06  California
24   77044.01        99281.34        140574.81    New York
34   46426.07       157693.92        210797.67  California
31   61136.38       152701.92         88218.23    New York
0   165349.20       136897.80        471784.10    New York
44   22177.74       154806.14         28334.72  California
27   72107.60       127864.55        353183.81    New York
33   55493.95       103057.49        214634.81     Florida
5   131876.90        99814.71        362861.36    New York
29   65605.48       153032.06        107138.38    New York
11  100671.96        91790.61        249744.55  California
36   28663.76       127056.21        201126.82     Florida
1   162597.70       151377.59        443898.53  California
21   78389.47       153773.43        299737.29    New York
2   153441.51       101145.55        407934.54     Florida
43   15505.73       127382.30         35534.17    New York
35   46014.02        85047.44        205517.64    New York
23   67532.53       105751.03        304768.73     Florida
40   28754.33       118546.05        172795.67  California
10  101913.08       110594.11        229160.95     Florida
22   73994.56       122782.75        303319.26     Florida
18   91749.16       114175.79        294919.57     Florida
49       0.00       116983.80         45173.06  California
20   76253.86       113867.30        298664.47  California
7   130298.13       145530.06        323876.68     Florida
42   23640.93        96189.63        148001.11  California
14  119943.24       156547.42        256512.92     Florida
28   66051.52       182645.56        118148.20     Florida
38   20229.59        65947.93        185265.10    New York

In [44]:
import joblib

In [45]:
joblib.dump(model , "state.lr")

['state.lr']